# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgAsZsbgpwVg1yYocbxDGVI_gGn6RCk_
"""

import random
file1 ="History is the systematic of the part"
file2 ="History the systematic study of the part this is the just for practice"

def jarcard_similarity(text1, text2):
  set1 = set(text1.split())
  set2 = set(text2.split())
  intersection = set1.intersection(set2)
  union = set1.union(set2)
  similarity = len(intersection) / len(union)
  return similarity, intersection


text1 = "History is the systematic study of the part"
text2 = "History the systematic study of the part this is the just for  practice"
similarity,common_words = jarcard_similarity(text1, text2)
print(f"similarity: {similarity:.2f}")
print(f"common words: {common_words}")